Enables programs to bring their own logger
ClockworkSoul/smudge pull request #18
Opened 2018-04-04 07:31 UTC by eelcocramer

Closes #17

2018-04-04 07:33 UTC, eelcocramer commented
Please note that the changes of PR #16 are also part of this PR!

2018-04-04 16:40 UTC, clockworksoul commented
Thanks for these! Apologies for not being able to review swiftly... work has been a little demanding lately. I'll have time this Saturday, though!

2018-04-08 17:54 UTC, clockworksoul commented
I'm generally in favor of adding this, but it does add the dependency on `github.com/rs/zerolog/log` and all of the problems that come with it. For that reason I've consciously avoided adding any dependencies at all (I have heard some encouraging news regarding Golang package management recently, however!)

That being said, If Smudge is going to see wider adoption I'll need to be a little more flexible, but I still want to keep external dependencies to a minimum.

2018-04-08 17:58 UTC, clockworksoul requested changes
Minor changes requested due to dependency introduction.

2018-04-08 17:58 UTC, clockworksoul commented on membership.go
> +func decodeMulticastAnnounceBytes(bytes []byte) (string, []byte, error) {
Now that this change is in master, would you mind rebasing and re-pushing?

2018-04-08 17:58 UTC, clockworksoul commented on smudge/smudge.go
> +	"github.com/rs/zerolog/log"
Adding this dependency breaks `make image` and the build instructions in the README. Would you mind adding the `go get` to the Dockerfile and update the README appropriately?

2018-04-08 18:44 UTC, eelcocramer commented on smudge/smudge.go
> +	"github.com/rs/zerolog/log"
You are right. I was not intended to commit `smudge.go`. It was my PoC test for adding an external logger. I will remove it from the PR.

2018-04-08 18:49 UTC, closed without merging